class XtdGearInfos {
    class CfgGlasses {
        //Facewear
        #include "XtdGearInfos\rhs3cb_facewear\CfgGlasses\rhs3cb_6m2_face.hpp"
        #include "XtdGearInfos\rhs3cb_facewear\CfgGlasses\rhs3cb_balaclava.hpp"
        #include "XtdGearInfos\rhs3cb_facewear\CfgGlasses\rhs3cb_goggles.hpp"
        #include "XtdGearInfos\rhs3cb_facewear\CfgGlasses\rhs3cb_oakley_goggles.hpp"
        #include "XtdGearInfos\rhs3cb_facewear\CfgGlasses\rhs3cb_shemagh.hpp"
    };

    class CfgVehicles {
        //Backpacks
        #include "XtdGearInfos\rhs3cb_backpack\CfgVehicles\rhs3cb_alicepack.hpp"
        #include "XtdGearInfos\rhs3cb_backpack\CfgVehicles\rhs3cb_eagleaiii.hpp"
        #include "XtdGearInfos\rhs3cb_backpack\CfgVehicles\rhs3cb_falconii.hpp"
        #include "XtdGearInfos\rhs3cb_backpack\CfgVehicles\rhs3cb_kitbag.hpp"
        #include "XtdGearInfos\rhs3cb_backpack\CfgVehicles\rhs3cb_rd54.hpp"
        #include "XtdGearInfos\rhs3cb_backpack\CfgVehicles\rhs3cb_rk_sht_30.hpp"
        #include "XtdGearInfos\rhs3cb_backpack\CfgVehicles\rhs3cb_rpg_carrier.hpp"
        #include "XtdGearInfos\rhs3cb_backpack\CfgVehicles\rhs3cb_sposn_tortila.hpp"
        #include "XtdGearInfos\rhs3cb_backpack\CfgVehicles\rhs3cb_umbts.hpp"
    };

    class CfgWeapons {
        //Headgear
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_6b26.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_6b27m.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_6b28.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_6b47.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_6b47_alt.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_6b7_1m.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_6m2_head.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_ach.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_acvc.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_altyn.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_bandana.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_beanie.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_beret_afrf.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_beret_saf.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_booniehat.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_bowman.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_fast_ballistic.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_fast_maritime.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_fieldcap.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_fieldcap_m88.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_furazkha.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_hgu56p.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_kaska.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_lwh.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_m1_helm.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_m40_helm.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_m42_helm.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_m42_helm_cover.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_m43_cap.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_m59_85.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_m97.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_mich2000.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_pasgt.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_patrolcap.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_protech_sf.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_ssh68.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_stsh81.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_tsh4.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_utilitycap.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_vkpo_cap.hpp"
        #include "XtdGearInfos\rhs3cb_headgear\CfgWeapons\rhs3cb_zsh7a.hpp"

        //Uniforms
        #include "XtdGearInfos\rhs3cb_uniform\CfgWeapons\rhs3cb_6sh122.hpp"
        #include "XtdGearInfos\rhs3cb_uniform\CfgWeapons\rhs3cb_FROG.hpp"
        #include "XtdGearInfos\rhs3cb_uniform\CfgWeapons\rhs3cb_acu.hpp"
        #include "XtdGearInfos\rhs3cb_uniform\CfgWeapons\rhs3cb_cu.hpp"
        #include "XtdGearInfos\rhs3cb_uniform\CfgWeapons\rhs3cb_df15_2.hpp"
        #include "XtdGearInfos\rhs3cb_uniform\CfgWeapons\rhs3cb_df15_saf.hpp"
        #include "XtdGearInfos\rhs3cb_uniform\CfgWeapons\rhs3cb_emr.hpp"
        #include "XtdGearInfos\rhs3cb_uniform\CfgWeapons\rhs3cb_flora.hpp"
        #include "XtdGearInfos\rhs3cb_uniform\CfgWeapons\rhs3cb_g3.hpp"
        #include "XtdGearInfos\rhs3cb_uniform\CfgWeapons\rhs3cb_gorka_1.hpp"
        #include "XtdGearInfos\rhs3cb_uniform\CfgWeapons\rhs3cb_gorka_r.hpp"
        #include "XtdGearInfos\rhs3cb_uniform\CfgWeapons\rhs3cb_m10.hpp"
        #include "XtdGearInfos\rhs3cb_uniform\CfgWeapons\rhs3cb_m88.hpp"
        #include "XtdGearInfos\rhs3cb_uniform\CfgWeapons\rhs3cb_m88_vdv.hpp"
        #include "XtdGearInfos\rhs3cb_uniform\CfgWeapons\rhs3cb_m93.hpp"
        #include "XtdGearInfos\rhs3cb_uniform\CfgWeapons\rhs3cb_vkpo.hpp"

        //Vests
        #include "XtdGearInfos\rhs3cb_vest\CfgWeapons\rhs3cb_6b13.hpp"
        #include "XtdGearInfos\rhs3cb_vest\CfgWeapons\rhs3cb_6b2.hpp"
        #include "XtdGearInfos\rhs3cb_vest\CfgWeapons\rhs3cb_6b23.hpp"
        #include "XtdGearInfos\rhs3cb_vest\CfgWeapons\rhs3cb_6b3.hpp"
        #include "XtdGearInfos\rhs3cb_vest\CfgWeapons\rhs3cb_6b45.hpp"
        #include "XtdGearInfos\rhs3cb_vest\CfgWeapons\rhs3cb_6b5_19.hpp"
        #include "XtdGearInfos\rhs3cb_vest\CfgWeapons\rhs3cb_6sh117.hpp"
        #include "XtdGearInfos\rhs3cb_vest\CfgWeapons\rhs3cb_6sh92.hpp"
        #include "XtdGearInfos\rhs3cb_vest\CfgWeapons\rhs3cb_belt_equip.hpp"
        #include "XtdGearInfos\rhs3cb_vest\CfgWeapons\rhs3cb_chicom.hpp"
        #include "XtdGearInfos\rhs3cb_vest\CfgWeapons\rhs3cb_iotv.hpp"
        #include "XtdGearInfos\rhs3cb_vest\CfgWeapons\rhs3cb_lifchik.hpp"
        #include "XtdGearInfos\rhs3cb_vest\CfgWeapons\rhs3cb_mbav.hpp"
        #include "XtdGearInfos\rhs3cb_vest\CfgWeapons\rhs3cb_otv.hpp"
        #include "XtdGearInfos\rhs3cb_vest\CfgWeapons\rhs3cb_pbb_m12.hpp"
        #include "XtdGearInfos\rhs3cb_vest\CfgWeapons\rhs3cb_pbb_m98.hpp"
        #include "XtdGearInfos\rhs3cb_vest\CfgWeapons\rhs3cb_pbb_m99t.hpp"
        #include "XtdGearInfos\rhs3cb_vest\CfgWeapons\rhs3cb_plateframe.hpp"
        #include "XtdGearInfos\rhs3cb_vest\CfgWeapons\rhs3cb_spc.hpp"
        #include "XtdGearInfos\rhs3cb_vest\CfgWeapons\rhs3cb_spcs.hpp"
        #include "XtdGearInfos\rhs3cb_vest\CfgWeapons\rhs3cb_sus_equip.hpp"

        //NVG
        #include "XtdGearInfos\rhs3cb_nvg\CfgWeapons\rhs3cb_6m2_nvg.hpp"

        //Weapons
        #include "XtdGearInfos\rhs3cb_weapon\CfgWeapons\rhs3cb_SCARH_CQC.hpp"
        #include "XtdGearInfos\rhs3cb_weapon\CfgWeapons\rhs3cb_SCARH_LB.hpp"
        #include "XtdGearInfos\rhs3cb_weapon\CfgWeapons\rhs3cb_SCARH_STD.hpp"
    };
};
