class XtdGearInfos {
    class CfgGlasses {
        //Facewear
        #include "XtdGearInfos\rhs_facewear\CfgGlasses\rhs_6m2_face.hpp"
        #include "XtdGearInfos\rhs_facewear\CfgGlasses\rhs_balaclava.hpp"
        #include "XtdGearInfos\rhs_facewear\CfgGlasses\rhs_goggles.hpp"
        #include "XtdGearInfos\rhs_facewear\CfgGlasses\rhs_oakley_goggles.hpp"
        #include "XtdGearInfos\rhs_facewear\CfgGlasses\rhs_shemagh.hpp"
    };

    class CfgVehicles {
        //Backpacks
        #include "XtdGearInfos\rhs_backpack\CfgVehicles\rhs_alicepack.hpp"
        #include "XtdGearInfos\rhs_backpack\CfgVehicles\rhs_eagleaiii.hpp"
        #include "XtdGearInfos\rhs_backpack\CfgVehicles\rhs_falconii.hpp"
        #include "XtdGearInfos\rhs_backpack\CfgVehicles\rhs_kitbag.hpp"
        #include "XtdGearInfos\rhs_backpack\CfgVehicles\rhs_rd54.hpp"
        #include "XtdGearInfos\rhs_backpack\CfgVehicles\rhs_rk_sht_30.hpp"
        #include "XtdGearInfos\rhs_backpack\CfgVehicles\rhs_rpg_carrier.hpp"
        #include "XtdGearInfos\rhs_backpack\CfgVehicles\rhs_sposn_tortila.hpp"
        #include "XtdGearInfos\rhs_backpack\CfgVehicles\rhs_umbts.hpp"
    };

    class CfgWeapons {
        //Headgear
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_6b26.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_6b27m.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_6b28.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_6b47.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_6b47_alt.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_6b7_1m.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_6m2_head.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_ach.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_acvc.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_altyn.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_bandana.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_beanie.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_beret_afrf.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_beret_saf.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_booniehat.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_bowman.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_fast_ballistic.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_fast_maritime.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_fieldcap.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_fieldcap_m88.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_furazkha.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_hgu56p.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_kaska.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_lwh.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_m1_helm.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_m40_helm.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_m42_helm.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_m42_helm_cover.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_m43_cap.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_m59_85.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_m97.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_mich2000.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_pasgt.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_patrolcap.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_protech_sf.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_ssh68.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_stsh81.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_tsh4.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_utilitycap.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_vkpo_cap.hpp"
        #include "XtdGearInfos\rhs_headgear\CfgWeapons\rhs_zsh7a.hpp"

        //Uniforms
        #include "XtdGearInfos\rhs_uniform\CfgWeapons\rhs_6sh122.hpp"
        #include "XtdGearInfos\rhs_uniform\CfgWeapons\rhs_FROG.hpp"
        #include "XtdGearInfos\rhs_uniform\CfgWeapons\rhs_acu.hpp"
        #include "XtdGearInfos\rhs_uniform\CfgWeapons\rhs_cu.hpp"
        #include "XtdGearInfos\rhs_uniform\CfgWeapons\rhs_df15_2.hpp"
        #include "XtdGearInfos\rhs_uniform\CfgWeapons\rhs_df15_saf.hpp"
        #include "XtdGearInfos\rhs_uniform\CfgWeapons\rhs_emr.hpp"
        #include "XtdGearInfos\rhs_uniform\CfgWeapons\rhs_flora.hpp"
        #include "XtdGearInfos\rhs_uniform\CfgWeapons\rhs_g3.hpp"
        #include "XtdGearInfos\rhs_uniform\CfgWeapons\rhs_gorka_1.hpp"
        #include "XtdGearInfos\rhs_uniform\CfgWeapons\rhs_gorka_r.hpp"
        #include "XtdGearInfos\rhs_uniform\CfgWeapons\rhs_m10.hpp"
        #include "XtdGearInfos\rhs_uniform\CfgWeapons\rhs_m88.hpp"
        #include "XtdGearInfos\rhs_uniform\CfgWeapons\rhs_m88_vdv.hpp"
        #include "XtdGearInfos\rhs_uniform\CfgWeapons\rhs_m93.hpp"
        #include "XtdGearInfos\rhs_uniform\CfgWeapons\rhs_vkpo.hpp"

        //Vests
        #include "XtdGearInfos\rhs_vest\CfgWeapons\rhs_6b13.hpp"
        #include "XtdGearInfos\rhs_vest\CfgWeapons\rhs_6b2.hpp"
        #include "XtdGearInfos\rhs_vest\CfgWeapons\rhs_6b23.hpp"
        #include "XtdGearInfos\rhs_vest\CfgWeapons\rhs_6b3.hpp"
        #include "XtdGearInfos\rhs_vest\CfgWeapons\rhs_6b45.hpp"
        #include "XtdGearInfos\rhs_vest\CfgWeapons\rhs_6b5_19.hpp"
        #include "XtdGearInfos\rhs_vest\CfgWeapons\rhs_6sh117.hpp"
        #include "XtdGearInfos\rhs_vest\CfgWeapons\rhs_6sh92.hpp"
        #include "XtdGearInfos\rhs_vest\CfgWeapons\rhs_belt_equip.hpp"
        #include "XtdGearInfos\rhs_vest\CfgWeapons\rhs_chicom.hpp"
        #include "XtdGearInfos\rhs_vest\CfgWeapons\rhs_iotv.hpp"
        #include "XtdGearInfos\rhs_vest\CfgWeapons\rhs_lifchik.hpp"
        #include "XtdGearInfos\rhs_vest\CfgWeapons\rhs_mbav.hpp"
        #include "XtdGearInfos\rhs_vest\CfgWeapons\rhs_otv.hpp"
        #include "XtdGearInfos\rhs_vest\CfgWeapons\rhs_pbb_m12.hpp"
        #include "XtdGearInfos\rhs_vest\CfgWeapons\rhs_pbb_m98.hpp"
        #include "XtdGearInfos\rhs_vest\CfgWeapons\rhs_pbb_m99t.hpp"
        #include "XtdGearInfos\rhs_vest\CfgWeapons\rhs_plateframe.hpp"
        #include "XtdGearInfos\rhs_vest\CfgWeapons\rhs_spc.hpp"
        #include "XtdGearInfos\rhs_vest\CfgWeapons\rhs_spcs.hpp"
        #include "XtdGearInfos\rhs_vest\CfgWeapons\rhs_sus_equip.hpp"

        //NVG
        #include "XtdGearInfos\rhs_nvg\CfgWeapons\rhs_6m2_nvg.hpp"

        //Weapons
        #include "XtdGearInfos\rhs_weapon\CfgWeapons\rhs_SCARH_CQC.hpp"
        #include "XtdGearInfos\rhs_weapon\CfgWeapons\rhs_SCARH_LB.hpp"
        #include "XtdGearInfos\rhs_weapon\CfgWeapons\rhs_SCARH_STD.hpp"
    };
};
