class XtdGearModels {
    #include "XtdGearModels_Common.hpp"
    class CfgGlasses {
         #include "XtdGearModels\usp_gear_acc\CfgGlasses\USP_THERMAL.hpp"
         #include "XtdGearModels\usp_gear_body\CfgGlasses\USP_OVERLORD.hpp"
         #include "XtdGearModels\usp_gear_body\CfgGlasses\USP_SUUNTO.hpp"
         #include "XtdGearModels\usp_gear_body\CfgGlasses\USP_WRISTCOACH.hpp"
         #include "XtdGearModels\usp_gear_face\CfgGlasses\USP_ADVANCER.hpp"
         #include "XtdGearModels\usp_gear_face\CfgGlasses\USP_BALACLAVA.hpp"
         #include "XtdGearModels\usp_gear_face\CfgGlasses\USP_BALACLAVA2.hpp"
         #include "XtdGearModels\usp_gear_face\CfgGlasses\USP_CROSSBOW.hpp"
         #include "XtdGearModels\usp_gear_face\CfgGlasses\USP_DETCORD.hpp"
         #include "XtdGearModels\usp_gear_face\CfgGlasses\USP_FM12.hpp"
         #include "XtdGearModels\usp_gear_face\CfgGlasses\USP_GATORZ.hpp"
         #include "XtdGearModels\usp_gear_face\CfgGlasses\USP_GP21.hpp"
         #include "XtdGearModels\usp_gear_face\CfgGlasses\USP_GP21_BLK.hpp"
         #include "XtdGearModels\usp_gear_face\CfgGlasses\USP_M50.hpp"
         #include "XtdGearModels\usp_gear_face\CfgGlasses\USP_MFRAME.hpp"
         #include "XtdGearModels\usp_gear_face\CfgGlasses\USP_OAKLEY_SI2.hpp"
         #include "XtdGearModels\usp_gear_face\CfgGlasses\USP_RAID.hpp"
         #include "XtdGearModels\usp_gear_face\CfgGlasses\USP_SHEMAGH.hpp"
         #include "XtdGearModels\usp_gear_face\CfgGlasses\USP_SOLR.hpp"
         #include "XtdGearModels\usp_gear_face\CfgGlasses\USP_SOTR.hpp"
         #include "XtdGearModels\usp_gear_face\CfgGlasses\USP_SOTR_SM.hpp"
         #include "XtdGearModels\usp_gear_face\CfgGlasses\USP_STRAIGHTJACKET.hpp"
    };
    class CfgVehicles {
         #include "XtdGearModels\usp_gear_pack\CfgVehicles\USP_45L_RUCKSACK.hpp"
         #include "XtdGearModels\usp_gear_pack\CfgVehicles\USP_HYDROPACK.hpp"
         #include "XtdGearModels\usp_gear_pack\CfgVehicles\USP_PACK_BREACHER.hpp"
         #include "XtdGearModels\usp_gear_pack\CfgVehicles\USP_PATROL_PACK.hpp"
         #include "XtdGearModels\usp_gear_pack\CfgVehicles\USP_ROLLFLAG.hpp"
         #include "XtdGearModels\usp_gear_pack\CfgVehicles\USP_TACTICAL_PACK.hpp"
         #include "XtdGearModels\usp_gear_pack\CfgVehicles\USP_ZIPON_PANEL.hpp"
         #include "XtdGearModels\usp_gear_vest\CfgVehicles\USP_CRYE_BELT_PACK.hpp"
    };
    class CfgWeapons {
         #include "XtdGearModels\usp_gear_acc\CfgWeapons\USP_COUNTERWEIGHT.hpp"
         #include "XtdGearModels\usp_gear_acc\CfgWeapons\USP_EARMUFF.hpp"
         #include "XtdGearModels\usp_gear_acc\CfgWeapons\USP_FACESHIELD.hpp"
         #include "XtdGearModels\usp_gear_acc\CfgWeapons\USP_FAST_COVER.hpp"
         #include "XtdGearModels\usp_gear_acc\CfgWeapons\USP_GOGGLE_COVER.hpp"
         #include "XtdGearModels\usp_gear_acc\CfgWeapons\USP_GUNSIGHT.hpp"
         #include "XtdGearModels\usp_gear_acc\CfgWeapons\USP_MECHANIX.hpp"
         #include "XtdGearModels\usp_gear_acc\CfgWeapons\USP_MOHOC.hpp"
         #include "XtdGearModels\usp_gear_acc\CfgWeapons\USP_NIGHTCAP.hpp"
         #include "XtdGearModels\usp_gear_acc\CfgWeapons\USP_OVERLORD.hpp"
         #include "XtdGearModels\usp_gear_body\CfgWeapons\USP_G3C.hpp"
         #include "XtdGearModels\usp_gear_body\CfgWeapons\USP_G3F.hpp"
         #include "XtdGearModels\usp_gear_body\CfgWeapons\USP_OVERWHITE_G3C.hpp"
         #include "XtdGearModels\usp_gear_body\CfgWeapons\USP_PCU_G3C.hpp"
         #include "XtdGearModels\usp_gear_body\CfgWeapons\USP_RUGBY_G3C.hpp"
         #include "XtdGearModels\usp_gear_body\CfgWeapons\USP_SOFTSHELL_G3C.hpp"
         #include "XtdGearModels\usp_gear_body\CfgWeapons\USP_TSHIRT_G3C.hpp"
         #include "XtdGearModels\usp_gear_head\CfgWeapons\USP_A2_BANDANA.hpp"
         #include "XtdGearModels\usp_gear_head\CfgWeapons\USP_A2_BOONIE_HAT.hpp"
         #include "XtdGearModels\usp_gear_head\CfgWeapons\USP_A2_PATROL_CAP.hpp"
         #include "XtdGearModels\usp_gear_head\CfgWeapons\USP_A2_WATCHCAP.hpp"
         #include "XtdGearModels\usp_gear_head\CfgWeapons\USP_AIRFRAME.hpp"
         #include "XtdGearModels\usp_gear_head\CfgWeapons\USP_BASEBALL.hpp"
         #include "XtdGearModels\usp_gear_head\CfgWeapons\USP_BOONIE_HAT.hpp"
         #include "XtdGearModels\usp_gear_head\CfgWeapons\USP_HEAD_MICH_TC2002_TAN.hpp"
         #include "XtdGearModels\usp_gear_head\CfgWeapons\USP_HEAD_RBH_ATTACK_TAN.hpp"
         #include "XtdGearModels\usp_gear_head\CfgWeapons\USP_MICH_TC2000.hpp"
         #include "XtdGearModels\usp_gear_head\CfgWeapons\USP_OPS_FASTXP.hpp"
         #include "XtdGearModels\usp_gear_head\CfgWeapons\USP_OPSCORE_FAST.hpp"
         #include "XtdGearModels\usp_gear_head\CfgWeapons\USP_OPSCORE_FASTFCV.hpp"
         #include "XtdGearModels\usp_gear_head\CfgWeapons\USP_PAKOL_HAT.hpp"
         #include "XtdGearModels\usp_gear_head\CfgWeapons\USP_PELTOR_COMTAC3.hpp"
         #include "XtdGearModels\usp_gear_head\CfgWeapons\USP_THM_BEANIE.hpp"
         #include "XtdGearModels\usp_gear_nvg\CfgWeapons\USP_ACC_GPNVG18.hpp"
         #include "XtdGearModels\usp_gear_nvg\CfgWeapons\USP_PVS31.hpp"
         #include "XtdGearModels\usp_gear_vest\CfgWeapons\USP_CRYE_CPC.hpp"
         #include "XtdGearModels\usp_gear_vest\CfgWeapons\USP_CRYE_JPC.hpp"
         #include "XtdGearModels\usp_gear_vest\CfgWeapons\USP_CRYE_NCPC.hpp"
         #include "XtdGearModels\usp_gear_vest\CfgWeapons\USP_EAGLE_MBAV.hpp"
         #include "XtdGearModels\usp_gear_vest\CfgWeapons\USP_EAGLE_MMAC_FAST.hpp"
         #include "XtdGearModels\usp_gear_vest\CfgWeapons\USP_VEST_PLATEFRAME.hpp"
         #include "XtdGearModels\usp_gear_vest\CfgWeapons\USP_VEST_STRANDHOGG.hpp"
         #include "XtdGearModels\usp_gear_vest\CfgWeapons\USP_VEST_STRANDHOGG2.hpp"
    };
};
