class XtdGearInfos {
    class CfgGlasses {
        //Facewear

    };

    class CfgVehicles {
        //Backpacks

    };

    class CfgWeapons {
        //Headgear

        //Uniforms

        //Vests

        //NVG

        // Weapons : Primaries
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_acr_68.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_acr_556.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_acr_c_68.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_acr_c_556.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_acr_c_eglm_68.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_acr_c_eglm_556.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_acr_dmr_68.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_acr_dmr_556.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_acr_eglm_68.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_acr_eglm_556.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_ak_47n.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_ak_47n_gp25.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_akmsn.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_akmsn_gp25.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_aks.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_aks_74n.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_aks_74n_gp25.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_aks_74u.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_ak_12.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_ak_12_gp34.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_ak_15.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_ak_15_gp34.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_ak_19.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_ak_19_gp34.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_ak_74m.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_ak_74m_gp25.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_ak_74n.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_ak_74n_gp25.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_ak_101.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_ak_101_gp25.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_ak_102.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_ak_103.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_ak_103_gp25.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_ak_104.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_ak_105.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_ak_107.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_ak_107_gp25.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_ak_108.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_ak_108_gp25.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_ak_109.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_ak_109_gp25.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_akmn.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_akmn_gp25.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_as_val.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_cz_550.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_cz_584.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_cz_805_bren_a1.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_cz_805_bren_a1_g1.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_cz_805_bren_a2.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_cz_807_8.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_cz_807_14.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_cz_807_14_gl.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_cz_bren_2_8.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_cz_bren_2_11.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_cz_bren_2_11_gl.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_cz_bren_2_14.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_cz_bren_2_14_gl.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_sa58_osw.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_saiga_12k.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_saiga_mk03.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_sks.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_sr3m_vikhr.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_stg_58.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_svd.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_type_56.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_vss_vintorez.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_x95.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_xm8_carbine.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_xm8_compact.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_m60e4.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_mac_10.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_mag_6020.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_mg3.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_mg36.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_mk16_cqc.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_mk16_cqc_eglm.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_mk16_std.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_mk16_std_eglm.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_mk16_sv.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_mk17_cqc.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_mk17_cqc_eglm.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_mk17_std.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_mk17_std_eglm.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_mk17_sv.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_mk14_mod_0.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_mk48_mod_0.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_mp5a5.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_mp7a1.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_no4_mki.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_g36.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_g36_ag36.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_g36a3.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_g36a3_ag36.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_g36c.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_g36ca3 .hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_g36e.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_g36k.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_g36k_ag36.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_g36k_ksk.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_g36ka3.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_fal_50_00.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_fal_50_61.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_fal_50_62.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_fal_50_63.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_fal_g.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_fal_osw.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_famas_f1.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_fort_224.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_g1.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_g3a3.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_g22.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_hk416.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_hk416_m203.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_hk416_m320.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_hk416_cqc.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_hk416_cqc_m203.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_hk416_cqc_m320.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_hk417_cqc.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_hk417_cqc_m203.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_hk417_cqc_m320.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_hk417_dmr.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_klec.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_l7a2.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_l85a2.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_l115a3.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_l129a1.hpp"

        // Weapons : Secondaries

        // Weapons : Launchers"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_m72a6.hpp"
        #include "XtdGearInfos\cup_weapon\CfgWeapons\cup_mk153_smaw.hpp"

    };
};
