class XtdGearModels {
    #include "XtdGearModels_Common.hpp"
    class CfgGlasses {
        //Facewear

    };

    class CfgVehicles {
        //Backpacks

    };

    class CfgWeapons {
        //Headgear

        //Uniforms

        //Vests

        //NVG

        // Weapons : Primaries
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_acr_68.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_acr_556.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_acr_c_68.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_acr_c_556.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_acr_c_eglm_68.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_acr_c_eglm_556.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_acr_dmr_68.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_acr_dmr_556.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_acr_eglm_68.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_acr_eglm_556.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_ak_47n.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_ak_47n_gp25.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_akmsn.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_akmsn_gp25.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_aks.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_aks_74n.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_aks_74n_gp25.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_aks_74u.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_ak_12.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_ak_12_gp34.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_ak_15.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_ak_15_gp34.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_ak_19.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_ak_19_gp34.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_ak_74m.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_ak_74m_gp25.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_ak_74n.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_ak_74n_gp25.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_ak_101.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_ak_101_gp25.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_ak_102.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_ak_103.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_ak_103_gp25.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_ak_104.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_ak_105.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_ak_107.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_ak_107_gp25.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_ak_108.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_ak_108_gp25.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_ak_109.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_ak_109_gp25.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_akmn.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_akmn_gp25.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_as_val.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_cz_550.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_cz_584.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_cz_805_bren_a1.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_cz_805_bren_a1_g1.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_cz_805_bren_a2.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_cz_807_8.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_cz_807_14.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_cz_807_14_gl.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_cz_bren_2_8.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_cz_bren_2_11.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_cz_bren_2_11_gl.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_cz_bren_2_14.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_cz_bren_2_14_gl.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_sa58_osw.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_saiga_12k.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_saiga_mk03.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_sks.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_sr3m_vikhr.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_stg_58.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_svd.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_type_56.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_vss_vintorez.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_x95.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_xm8_carbine.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_xm8_compact.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_m60e4.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_mac_10.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_mag_6020.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_mg3.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_mg36.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_mk16_cqc.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_mk16_cqc_eglm.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_mk16_std.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_mk16_std_eglm.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_mk16_sv.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_mk17_cqc.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_mk17_cqc_eglm.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_mk17_std.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_mk17_std_eglm.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_mk17_sv.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_mk14_mod_0.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_mk48_mod_0.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_mp5a5.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_mp7a1.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_no4_mki.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_g36.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_g36_ag36.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_g36a3.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_g36a3_ag36.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_g36c.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_g36ca3 .hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_g36e.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_g36k.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_g36k_ag36.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_g36k_ksk.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_g36ka3.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_fal_50_00.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_fal_50_61.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_fal_50_62.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_fal_50_63.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_fal_g.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_fal_osw.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_famas_f1.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_fort_224.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_g1.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_g3a3.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_g22.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_hk416.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_hk416_m203.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_hk416_m320.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_hk416_cqc.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_hk416_cqc_m203.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_hk416_cqc_m320.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_hk417_cqc.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_hk417_cqc_m203.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_hk417_cqc_m320.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_hk417_dmr.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_klec.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_l7a2.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_l85a2.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_l115a3.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_l129a1.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_rpk.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_rpk_74.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_rpk_74m.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_romat.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_r11_rsass.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_pp_1901_vityaz.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_m16a1_m203.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_m107.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_m110.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_m1014.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_m1014_entry.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_m3a1.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_m4_sbr.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_m16a4.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_m21_sws.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_m27_iar.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_m2010.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_m24.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_m4a1_11_3.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_m4a1_14_5.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_m4a1.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_m4a1_m203.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_m4a1_sopmod.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_pkm.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_pkp.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_savz_58_carbine.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_savz_58_sporter.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_savz_58p.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_savz_58s.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_savz_58v.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_savz_58v_ris.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_savz_58v_ris_g1.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_savz_61.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_g17.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_m17.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_mp7a1_sec.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_savz_61_sec.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_taurus.hpp"

        // Weapons : Secondaries

        // Weapons : Launchers
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_m72a6.hpp"
        #include "XtdGearModels\cup_weapon\CfgWeapons\cup_mk153_smaw.hpp"

    };
};
