class XtdGearModels {
    #include "XtdGearModels_Common.hpp"
    class CfgGlasses {
        //Facewear
        #include "XtdGearModels\rhs_facewear\CfgGlasses\rhs_6m2_face.hpp"
        #include "XtdGearModels\rhs_facewear\CfgGlasses\rhs_balaclava.hpp"
        #include "XtdGearModels\rhs_facewear\CfgGlasses\rhs_goggles.hpp"
        #include "XtdGearModels\rhs_facewear\CfgGlasses\rhs_oakley_goggles.hpp"
        #include "XtdGearModels\rhs_facewear\CfgGlasses\rhs_shemagh.hpp"
    };

    class CfgVehicles {
        //Backpacks
        #include "XtdGearModels\rhs_backpack\CfgVehicles\rhs_alicepack.hpp"
        #include "XtdGearModels\rhs_backpack\CfgVehicles\rhs_eagleaiii.hpp"
        #include "XtdGearModels\rhs_backpack\CfgVehicles\rhs_falconii.hpp"
        #include "XtdGearModels\rhs_backpack\CfgVehicles\rhs_kitbag.hpp"
        #include "XtdGearModels\rhs_backpack\CfgVehicles\rhs_rd54.hpp"
        #include "XtdGearModels\rhs_backpack\CfgVehicles\rhs_rk_sht_30.hpp"
        #include "XtdGearModels\rhs_backpack\CfgVehicles\rhs_rpg_carrier.hpp"
        #include "XtdGearModels\rhs_backpack\CfgVehicles\rhs_sposn_tortila.hpp"
        #include "XtdGearModels\rhs_backpack\CfgVehicles\rhs_umbts.hpp"
    };

    class CfgWeapons {
        //Headgear
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_6b26.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_6b27m.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_6b28.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_6b47.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_6b47_alt.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_6b7_1m.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_6m2_head.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_ach.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_acvc.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_altyn.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_bandana.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_beanie.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_beret_afrf.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_beret_saf.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_booniehat.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_bowman.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_fast_ballistic.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_fast_maritime.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_fieldcap.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_fieldcap_m88.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_furazkha.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_hgu56p.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_kaska.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_lwh.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_m1_helm.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_m40_helm.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_m42_helm.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_m42_helm_cover.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_m43_cap.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_m59_85.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_m97.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_mich2000.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_pasgt.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_patrolcap.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_protech_sf.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_ssh68.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_stsh81.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_tsh4.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_utilitycap.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_vkpo_cap.hpp"
        #include "XtdGearModels\rhs_headgear\CfgWeapons\rhs_zsh7a.hpp"

        //Uniforms
        #include "XtdGearModels\rhs_uniform\CfgWeapons\rhs_6sh122.hpp"
        #include "XtdGearModels\rhs_uniform\CfgWeapons\rhs_FROG.hpp"
        #include "XtdGearModels\rhs_uniform\CfgWeapons\rhs_acu.hpp"
        #include "XtdGearModels\rhs_uniform\CfgWeapons\rhs_cu.hpp"
        #include "XtdGearModels\rhs_uniform\CfgWeapons\rhs_df15_2.hpp"
        #include "XtdGearModels\rhs_uniform\CfgWeapons\rhs_df15_saf.hpp"
        #include "XtdGearModels\rhs_uniform\CfgWeapons\rhs_emr.hpp"
        #include "XtdGearModels\rhs_uniform\CfgWeapons\rhs_flora.hpp"
        #include "XtdGearModels\rhs_uniform\CfgWeapons\rhs_g3.hpp"
        #include "XtdGearModels\rhs_uniform\CfgWeapons\rhs_gorka_1.hpp"
        #include "XtdGearModels\rhs_uniform\CfgWeapons\rhs_gorka_r.hpp"
        #include "XtdGearModels\rhs_uniform\CfgWeapons\rhs_gue_unif_tna.hpp"
        #include "XtdGearModels\rhs_uniform\CfgWeapons\rhs_m10.hpp"
        #include "XtdGearModels\rhs_uniform\CfgWeapons\rhs_m88.hpp"
        #include "XtdGearModels\rhs_uniform\CfgWeapons\rhs_m88_cdf.hpp"
        #include "XtdGearModels\rhs_uniform\CfgWeapons\rhs_m88_vdv.hpp"
        #include "XtdGearModels\rhs_uniform\CfgWeapons\rhs_m93.hpp"
        #include "XtdGearModels\rhs_uniform\CfgWeapons\rhs_vkpo.hpp"

        //Vests
        #include "XtdGearModels\rhs_vest\CfgWeapons\rhs_6b13.hpp"
        #include "XtdGearModels\rhs_vest\CfgWeapons\rhs_6b2.hpp"
        #include "XtdGearModels\rhs_vest\CfgWeapons\rhs_6b23.hpp"
        #include "XtdGearModels\rhs_vest\CfgWeapons\rhs_6b3.hpp"
        #include "XtdGearModels\rhs_vest\CfgWeapons\rhs_6b45.hpp"
        #include "XtdGearModels\rhs_vest\CfgWeapons\rhs_6b5_19.hpp"
        #include "XtdGearModels\rhs_vest\CfgWeapons\rhs_6sh117.hpp"
        #include "XtdGearModels\rhs_vest\CfgWeapons\rhs_6sh92.hpp"
        #include "XtdGearModels\rhs_vest\CfgWeapons\rhs_belt_equip.hpp"
        #include "XtdGearModels\rhs_vest\CfgWeapons\rhs_chicom.hpp"
        #include "XtdGearModels\rhs_vest\CfgWeapons\rhs_iotv.hpp"
        #include "XtdGearModels\rhs_vest\CfgWeapons\rhs_lifchik.hpp"
        #include "XtdGearModels\rhs_vest\CfgWeapons\rhs_mbav.hpp"
        #include "XtdGearModels\rhs_vest\CfgWeapons\rhs_otv.hpp"
        #include "XtdGearModels\rhs_vest\CfgWeapons\rhs_pbb_m12.hpp"
        #include "XtdGearModels\rhs_vest\CfgWeapons\rhs_pbb_m98.hpp"
        #include "XtdGearModels\rhs_vest\CfgWeapons\rhs_pbb_m99t.hpp"
        #include "XtdGearModels\rhs_vest\CfgWeapons\rhs_plateframe.hpp"
        #include "XtdGearModels\rhs_vest\CfgWeapons\rhs_spc.hpp"
        #include "XtdGearModels\rhs_vest\CfgWeapons\rhs_spcs.hpp"
        #include "XtdGearModels\rhs_vest\CfgWeapons\rhs_sus_equip.hpp"

        //NVG
        #include "XtdGearModels\rhs_nvg\CfgWeapons\rhs_6m2_nvg.hpp"

        // Weapons : Primaries
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_ak103.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_ak103_1.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_ak103_2.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_ak103_gp25.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_ak104.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_ak105.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_ak74.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_ak74m.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_ak74m_gp25.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_ak74n.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_ak74n_gp25.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_akmn.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_akmn_gp25.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_aks74n.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_aks74n_gp25.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_asval.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_hk416_d10.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_hk416_d145.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_l1a1.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_m107.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_m14.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_m16a4.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_m16a4_m203.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_m2010.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_m21a.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_m21a_pbg.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_m21s.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_m24.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_m27iar.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_m38.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_m4.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_m40a5.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_m4_m203.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_m4_m203s.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_m4a1.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_m4a1_blockII.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_m4a1_blockII_m203.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_m4a1_pip.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_m4a1_pip_m203s.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_mk11.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_mk11_ec.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_mk18.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_mp7a2.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_rpk74m.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_savz58p.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_savz58v.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_scarh_cqc.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_scarh_lb.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_scarh_std.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_socom16.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_svdm.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_svds.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_vhsd2.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_vhsd2_bg.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_vssvin.hpp"

        // Weapons : Secondaries
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_cz99.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_rsp30.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_mp7a2_folded.hpp"

        // Weapons : Launchers
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_m136.hpp"
        #include "XtdGearModels\rhs_weapon\CfgWeapons\rhs_smaw.hpp"

        // Binoculars
        #include "XtdGearModels\rhs_binoculars\CfgWeapons\rhs_lerca1200.hpp"
        #include "XtdGearModels\rhs_binoculars\CfgWeapons\rhs_m24_bino.hpp"
        #include "XtdGearModels\rhs_binoculars\CfgWeapons\rhs_tr8.hpp"
    };
};
