class USP_CRYE_AIRFRAME {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "none";
  iropt = "none";
  light = "none";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CP {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "yes";
  comms = "none";
  counterweight = "none";
  goggles = "none";
  iropt = "none";
  light = "none";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CPC3 {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "yes";
  comms = "CT3";
  counterweight = "none";
  goggles = "none";
  iropt = "none";
  light = "none";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CT3 {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "CT3";
  counterweight = "none";
  goggles = "none";
  iropt = "none";
  light = "none";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CM {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "none";
  iropt = "none";
  light = "none";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CMW {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "none";
  iropt = "none";
  light = "none";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CMWGU {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "GU";
  iropt = "none";
  light = "none";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CMWGUI {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "GU";
  iropt = "IR";
  light = "none";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CMWGUIS {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "GU";
  iropt = "IR";
  light = "SF";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CMWGUISV {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "GU";
  iropt = "IR";
  light = "SF";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CMWGUIT {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "GU";
  iropt = "IR";
  light = "TL";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CMWGUITV {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "GU";
  iropt = "IR";
  light = "TL";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CMWGUIV {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "GU";
  iropt = "IR";
  light = "none";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CMWGUS {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "GU";
  iropt = "none";
  light = "SF";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CMWGUSV {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "GU";
  iropt = "none";
  light = "SF";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CMWGUT {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "GU";
  iropt = "none";
  light = "TL";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CMWGUTV {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "GU";
  iropt = "none";
  light = "TL";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CMWGUV {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "GU";
  iropt = "none";
  light = "none";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CMWI {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "none";
  iropt = "IR";
  light = "none";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CMWIS {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "none";
  iropt = "IR";
  light = "SF";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CMWISV {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "none";
  iropt = "IR";
  light = "SF";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CMWIT {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "none";
  iropt = "IR";
  light = "TL";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CMWITV {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "none";
  iropt = "IR";
  light = "TL";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CMWIV {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "none";
  iropt = "IR";
  light = "none";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CMWS {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "none";
  iropt = "none";
  light = "SF";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CMWSV {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "none";
  iropt = "none";
  light = "SF";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CMWT {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "none";
  iropt = "none";
  light = "TL";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CMWTV {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "none";
  iropt = "none";
  light = "TL";
  vlopt = "VL";
};
//Conflict with USP_CRYE_AIRFRAME_CMWSV
//class USP_CRYE_AIRFRAME_CMWV {
//  model = "USP_AIRFRAME";
//  camera = "CM";
//  camo = "TAN";
//  chops = "no";
//  comms = "none";
//  counterweight = "CW";
//  goggles = "none";
//  iropt = "none";
//  light = "SF";
//  vlopt = "VL";
//};
class USP_CRYE_AIRFRAME_CMGU {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "GU";
  iropt = "none";
  light = "none";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CMGUI {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "GU";
  iropt = "IR";
  light = "none";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CMGUIS {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "GU";
  iropt = "IR";
  light = "SF";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CMGUISV {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "GU";
  iropt = "IR";
  light = "SF";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CMGUIT {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "GU";
  iropt = "IR";
  light = "TL";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CMGUITV {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "GU";
  iropt = "IR";
  light = "TL";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CMGUIV {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "GU";
  iropt = "IR";
  light = "none";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CMGUS {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "GU";
  iropt = "none";
  light = "SF";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CMGUSV {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "GU";
  iropt = "none";
  light = "SF";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CMGUT {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "GU";
  iropt = "none";
  light = "TL";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CMGUTV {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "GU";
  iropt = "none";
  light = "TL";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CMGUV {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "GU";
  iropt = "none";
  light = "none";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CMI {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "none";
  iropt = "IR";
  light = "none";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CMIS {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "none";
  iropt = "IR";
  light = "SF";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CMISV {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "none";
  iropt = "IR";
  light = "SF";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CMIT {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "none";
  iropt = "IR";
  light = "TL";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CMITV {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "none";
  iropt = "IR";
  light = "TL";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CMIV {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "none";
  iropt = "IR";
  light = "none";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CMS {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "none";
  iropt = "none";
  light = "SF";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CMSV {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "none";
  iropt = "none";
  light = "SF";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CMT {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "none";
  iropt = "none";
  light = "TL";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CMTV {
  model = "USP_AIRFRAME";
  camera = "CM";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "none";
  iropt = "none";
  light = "TL";
  vlopt = "VL";
};
//Conflict with USP_CRYE_AIRFRAME_CMSV
//class USP_CRYE_AIRFRAME_CMV {
//  model = "USP_AIRFRAME";
//  camera = "CM";
//  camo = "TAN";
//  chops = "no";
//  comms = "none";
//  counterweight = "none";
//  goggles = "none";
//  iropt = "none";
//  light = "SF";
//  vlopt = "VL";
//};
class USP_CRYE_AIRFRAME_CW {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "none";
  iropt = "none";
  light = "none";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CWGU {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "GU";
  iropt = "none";
  light = "none";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CWGUI {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "GU";
  iropt = "IR";
  light = "none";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CWGUIS {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "GU";
  iropt = "IR";
  light = "SF";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CWGUISV {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "GU";
  iropt = "IR";
  light = "SF";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CWGUIT {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "GU";
  iropt = "IR";
  light = "TL";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CWGUITV {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "GU";
  iropt = "IR";
  light = "TL";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CWGUIV {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "GU";
  iropt = "IR";
  light = "none";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CWGUS {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "GU";
  iropt = "none";
  light = "SF";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CWGUSV {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "GU";
  iropt = "none";
  light = "SF";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CWGUT {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "GU";
  iropt = "none";
  light = "TL";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CWGUTV {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "GU";
  iropt = "none";
  light = "TL";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CWI {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "none";
  iropt = "IR";
  light = "none";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CWIS {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "none";
  iropt = "IR";
  light = "SF";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CWISV {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "none";
  iropt = "IR";
  light = "SF";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CWIT {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "none";
  iropt = "IR";
  light = "TL";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CWITV {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "none";
  iropt = "IR";
  light = "TL";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CWIV {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "none";
  iropt = "IR";
  light = "none";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CWS {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "none";
  iropt = "none";
  light = "SF";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CWSV {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "none";
  iropt = "none";
  light = "SF";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CWT {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "none";
  iropt = "none";
  light = "TL";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_CWTV {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "none";
  iropt = "none";
  light = "TL";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_CWV {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "CW";
  goggles = "none";
  iropt = "none";
  light = "none";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_GU {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "GU";
  iropt = "none";
  light = "none";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_GUI {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "GU";
  iropt = "IR";
  light = "none";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_GUIS {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "GU";
  iropt = "IR";
  light = "SF";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_GUISV {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "GU";
  iropt = "IR";
  light = "SF";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_GUIT {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "GU";
  iropt = "IR";
  light = "TL";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_GUITV {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "GU";
  iropt = "IR";
  light = "TL";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_GUIV {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "GU";
  iropt = "IR";
  light = "none";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_GUS {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "GU";
  iropt = "none";
  light = "SF";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_GUSV {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "GU";
  iropt = "none";
  light = "SF";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_GUT {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "GU";
  iropt = "none";
  light = "TL";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_GUTV {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "GU";
  iropt = "none";
  light = "TL";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_GUV {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "GU";
  iropt = "none";
  light = "none";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_IR {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "none";
  iropt = "IR";
  light = "none";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_IRS {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "none";
  iropt = "IR";
  light = "SF";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_IRSV {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "none";
  iropt = "IR";
  light = "SF";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_IRT {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "none";
  iropt = "IR";
  light = "TL";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_IRTV {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "none";
  iropt = "IR";
  light = "TL";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_IRV {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "none";
  iropt = "IR";
  light = "none";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_SF {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "none";
  iropt = "none";
  light = "SF";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_SFV {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "none";
  iropt = "none";
  light = "SF";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_TL {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "none";
  iropt = "none";
  light = "TL";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_TLV {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "none";
  iropt = "none";
  light = "TL";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_VL {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "TAN";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "none";
  iropt = "none";
  light = "none";
  vlopt = "VL";
};
class USP_CRYE_AIRFRAME_BLK {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "BLK";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "none";
  iropt = "none";
  light = "none";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_MC {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "MC";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "none";
  iropt = "none";
  light = "none";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_MCD {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "MCD";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "none";
  iropt = "none";
  light = "none";
  vlopt = "none";
};
class USP_CRYE_AIRFRAME_OD {
  model = "USP_AIRFRAME";
  camera = "none";
  camo = "OD";
  chops = "no";
  comms = "none";
  counterweight = "none";
  goggles = "none";
  iropt = "none";
  light = "none";
  vlopt = "none";
};
