class XtdGearModels {
    #include "XtdGearModels_Common.hpp"
    class CfgGlasses {
         #include "XtdGearModels\amf_facewear\CfgGlasses\amf_balaclava.hpp"
    };
    class CfgVehicles {
         #include "XtdGearModels\amf_backpack\CfgVehicles\AMF_FELIN_BACKPACK.hpp"
         #include "XtdGearModels\amf_backpack\CfgVehicles\amf_tecpack_30L.hpp"
         #include "XtdGearModels\Amf_Backpack_Dog\CfgVehicles\AMF_backpack_dog.hpp"
         #include "XtdGearModels\amf_backpack_03\CfgVehicles\AMF_Bergen_F2.hpp"
         #include "XtdGearModels\amf_backpack_02\CfgVehicles\AMF_rush24_01.hpp"
    };
    class CfgWeapons {
         #include "XtdGearModels\amf_614\CfgWeapons\AMF_614_long_FS.hpp"
         #include "XtdGearModels\amf_614\CfgWeapons\AMF_614_short_FS.hpp"
         #include "XtdGearModels\amf_glock_17\CfgWeapons\AMF_Glock_17.hpp"
         #include "XtdGearModels\amf_headgear_02\CfgWeapons\AMF_F3.hpp"
         #include "XtdGearModels\amf_headgear_02\CfgWeapons\AMF_FELIN.hpp"
         #include "XtdGearModels\amf_headgear_02\CfgWeapons\AMF_TCNVG.hpp"
         #include "XtdGearModels\amf_vests4\CfgWeapons\amf_SMB.hpp"
         #include "XtdGearModels\AMF_headgear_06\CfgWeapons\AMF_Casque_F1.hpp"
         #include "XtdGearModels\AMF_headgear_06\CfgWeapons\AMF_SPECTRA.hpp"
         #include "XtdGearModels\Amf_Mask_Dog\CfgWeapons\AMF_Mask_dog.hpp"
         #include "XtdGearModels\amf_uniforms\CfgWeapons\amf_t4s2.hpp"
         #include "XtdGearModels\amf_uniforms\CfgWeapons\amf_uniform_f3.hpp"
         #include "XtdGearModels\amf_uniforms\CfgWeapons\amf_uniform_ubas.hpp"
         #include "XtdGearModels\amf_Vest_Dog\CfgWeapons\amf_GS_COLLAR.hpp"
         #include "XtdGearModels\amf_Vest_Dog\CfgWeapons\amf_MA_COLLAR.hpp"
         #include "XtdGearModels\amf_Vest_Dog\CfgWeapons\amf_Vest_Dog.hpp"
         #include "XtdGearModels\amf_714_Long\CfgWeapons\AMF_714_Long.hpp"
         #include "XtdGearModels\amf_714_short\CfgWeapons\AMF_714_short.hpp"
         #include "XtdGearModels\amf_headgear_04\CfgWeapons\AMF_opscore.hpp"
         #include "XtdGearModels\amf_headgear_04\CfgWeapons\AMF_opscore2.hpp"
         #include "XtdGearModels\amf_headgear_04\CfgWeapons\AMF_opscore3.hpp"
         #include "XtdGearModels\amf_headgear_04\CfgWeapons\AMF_opscore4.hpp"
         #include "XtdGearModels\amf_headgear_04\CfgWeapons\AMF_TC3000.hpp"
         #include "XtdGearModels\amf_headgear_04\CfgWeapons\AMF_TC3001.hpp"
         #include "XtdGearModels\amf_headgear_04\CfgWeapons\AMF_TC800.hpp"
         #include "XtdGearModels\amf_headgear_04\CfgWeapons\AMF_TC801.hpp"
         #include "XtdGearModels\amf_headgear_04\CfgWeapons\AMF_TC801_FS.hpp"
         #include "XtdGearModels\amf_headgear_05\CfgWeapons\AMF_ELNO_DH_586.hpp"
         #include "XtdGearModels\amf_scar_h\CfgWeapons\AMF_SCARH.hpp"
         #include "XtdGearModels\amf_scar_h\CfgWeapons\AMF_SCARL.hpp"
         #include "XtdGearModels\amf_uniforms02\CfgWeapons\amf_g3.hpp"
         #include "XtdGearModels\amf_vests2\CfgWeapons\amf_dcs.hpp"
         #include "XtdGearModels\amf_vests2\CfgWeapons\amf_jpc.hpp"
    };
};
